runtime: nodejs16
service: default

env_variables:
  URI_USER_SVC: https://user-service-dot-cs3219g20.as.r.appspot.com
  URI_MATCHING_SVC: https://matching-service-dot-cs3219g20.as.r.appspot.com
  URI_COLLAB_SVC: https://collaboration-service-dot-cs3219g20.as.r.appspot.com
  URI_QUESTION_SVC: https://question-service-dot-cs3219g20.as.r.appspot.com

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
