services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    links:
    - user-service
    - matching-service
    environment:
    - URI_USER_SVC=http://user-service:8000
    - URI_MATCHING_SVC=http://matching-service:8001
  user-service:
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - 8000:8000
    links:
    - mongodb
    - redis
  matching-service:
    container_name: matching-service
    build:
      context: ./matching-service
    ports:
      - 8001:8001
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - mongo:/data/db
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
    - 6379:6379
    volumes:
    - redis:/data
    - ./user-service/config/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mongo:
  redis:
