name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Start
        run: cd frontend && npm run start

  matching-service:
    name: Matching Service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: cd matching-service && npm install

      - name: Start
        run: cd matching-service && npm run start

  user-service:
    name: User Service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build
        run: cd user-service/cmd && go build -v ./...

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
      
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: '6.0'

      - name: Test
        run: cd user-service && go test -v ./...
        env:
          DB_URI: "mongodb://localhost:27017"
          DB_NAME: "user_service_test"
          CACHE_ADDRESS: "localhost:6379"
